lastupdatecheck: 0
recentrepos:
    - /Users/guru/projects/programs
    - /Users/guru/projects/programs.spare
    - /Users/guru/dotfiles
startuppopupversion: 5
lastversion: 0.52.0
customcommandshistory:
    - q
hidecommandlog: true
ignorewhitespaceindiffview: false
diffcontextsize: 3
renamesimilaritythreshold: 50
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
