color = ''
project-name = 'default'
[default]
account_id = 'acct_1AqoOKLppDrgctRE'
device_name = 'pacmookbro.lan'
display_name = 'RG - Payouts'
live_mode_api_key = 'rk_live_***********************************************************************************************YqiQ'
live_mode_key_expires_at = '2025-04-17'
live_mode_pub_key = 'pk_live_Q9w0U7NwWsQfProgh4hSG0Cc'
test_mode_api_key = 'rk_test_51AqoOKLppDrgctREfYTGbz4EcNau2QiUTeg98xWI07jwsHUEwxkKV4LGIR2g9fmbFIWy5mOIg5zt32uuemvONrEN00AL6TQOae'
test_mode_key_expires_at = '2025-04-17'
test_mode_pub_key = 'pk_test_5iP1vnZ1rMU8es8wWZLreY02'

